"""
Configuration des dimensions et proportions.
"""

# --- DIMENSIONS CARTES ---
CARD_ASPECT_RATIO = 0.714
CARD_HEIGHT_PERCENT = 0.20

# --- POSITIONS VERTICALES (Y) ---

# Joueur 2 (Haut)
P2_HAND_Y_PERCENT = 0.02
P2_BOARD_Y_PERCENT = 0.25
P2_PILE_Y_PERCENT = 0.05

# Joueur 1 (Bas)
P1_HAND_Y_PERCENT = 0.82
P1_BOARD_Y_PERCENT = 0.45
P1_PILE_Y_PERCENT = 0.75

# --- POSITIONS HORIZONTALES (X) ---
PILE_MARGIN_PERCENT = 0.02

# --- AUTRES ---
MARGIN_PERCENT = 0.02
GAP_PERCENT = 0.01
ANIMATION_SPEED = 15
ZOOM_FACTOR = 2.5